import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function SegundoPiso3D(props) {
  const { nodes, materials } = useGLTF("/maps/SegundoPiso.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh0.geometry}
        material={materials.mat0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh1.geometry}
        material={materials.mat1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh2.geometry}
        material={materials.mat2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh3.geometry}
        material={materials.mat3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh4.geometry}
        material={materials.mat4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh5.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh6.geometry}
        material={materials.mat6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh7.geometry}
        material={materials.mat7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh8.geometry}
        material={materials.mat8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh9.geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh10.geometry}
        material={materials.mat10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh11.geometry}
        material={materials.mat11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh12.geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh13.geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh14.geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh15.geometry}
        material={materials.mat15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh16.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh17.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh18.geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh19.geometry}
        material={materials.mat19}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh20.geometry}
        material={materials.mat20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh21.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh22.geometry}
        material={materials.mat22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh23.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh24.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh25.geometry}
        material={materials.mat25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh26.geometry}
        material={materials.mat26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh27.geometry}
        material={materials.mat27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh28.geometry}
        material={materials.mat28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh29.geometry}
        material={materials.mat29}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh30.geometry}
        material={materials.mat30}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh31.geometry}
        material={materials.mat31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh32.geometry}
        material={materials.mat32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh33.geometry}
        material={materials.mat33}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh34.geometry}
        material={materials.mat34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh35.geometry}
        material={materials.mat35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh36.geometry}
        material={materials.mat36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh37.geometry}
        material={materials.mat37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh38.geometry}
        material={materials.mat38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh39.geometry}
        material={materials.mat39}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh40.geometry}
        material={materials.mat40}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh41.geometry}
        material={materials.mat41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh42.geometry}
        material={materials.mat42}
      />
    </group>
  );
}

useGLTF.preload("/maps/SegundoPiso.glb");